financial_report:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "UP88733"
      user: "SHAWN021003"
      role: ACCOUNTADMIN
      database: ISE558_D3
      warehouse: COMPUTE_WH
      schema: PROJECT_DELIVERY_DM
      threads: 4
