{{ config(materialized='table') }}

SELECT
    ROW_NUMBER() OVER (ORDER BY PROJECTID) AS PROJECT_KEY,
    PROJECTID AS PROJECT_ID,
    NAME AS PROJECT_NAME,
    TYPE AS PROJECT_TYPE,
    STATUS AS PROJECT_STATUS,
    CLIENTID AS CLIENT_ID,
    UNITID AS BUSINESS_UNIT_ID,
    PLANNED_START_DATE,
    PLANNED_END_DATE,
    ACTUAL_START_DATE,
    ACTUAL_END_DATE,
    PLANNED_HOURS,
    ESTIMATED_BUDGET,
    PROGRESS AS PROJECT_PROGRESS
FROM CONSULTING_DB_INITIAL.CONSULTING.PROJECT
