{{ config(materialized='table') }}

SELECT
    ROW_NUMBER() OVER (ORDER BY BUSINESSUNITID) AS BUSINESS_UNIT_KEY,
    BUSINESSUNITID AS BUSINESS_UNIT_ID,
    BUSINESS_UNIT_NAME
FROM CONSULTING_DB_INITIAL.CONSULTING.BUSINESSUNIT
