{{ config(materialized='table') }}

SELECT
    ROW_NUMBER() OVER (ORDER BY DELIVERABLEID) AS DELIVERABLE_KEY,
    DELIVERABLEID AS DELIVERABLE_ID,
    PROJECTID AS PROJECT_ID,
    NAME AS DELIVERABLE_NAME,
    STATUS AS DELIVERABLE_STATUS,
    PLANNED_START_DATE,
    ACTUAL_START_DATE,
    DUE_DATE,
    SUBMISSION_DATE,
    INVOICED_DATE,
    PLANNED_HOURS,
    PRICE,
    PROGRESS AS DELIVERABLE_PROGRESS
FROM CONSULTING_DB_INITIAL.CONSULTING.DELIVERABLE
