{{ config(materialized='table') }}

SELECT
    ROW_NUMBER() OVER (ORDER BY CLIENTID) AS CLIENT_KEY,
    CLIENTID AS CLIENT_ID,
    CLIENT_NAME,
    LOCATIONID AS LOCATION_ID,
    PHONE_NUMBER,
    EMAIL
FROM CONSULTING_DB_INITIAL.CONSULTING.CLIENT
