{{ config(materialized='table') }}

WITH actual_hours_by_month AS (
    SELECT
        cd.DELIVERABLEID AS DELIVERABLE_ID,
        DATE_TRUNC('MONTH', TRY_TO_DATE(cd.DATE)) AS MONTH_START_DATE,
        SUM(cd.HOURS) AS ACTUAL_HOURS
    FROM CONSULTING_DB_INITIAL.CONSULTING.CONSULTANTDELIVERABLE cd
    WHERE TRY_TO_DATE(cd.DATE) IS NOT NULL
    GROUP BY
        cd.DELIVERABLEID,
        DATE_TRUNC('MONTH', TRY_TO_DATE(cd.DATE))
),

expenses_by_month AS (
    SELECT
        pe.PROJECTID AS PROJECT_ID,
        pe.DELIVERABLEID AS DELIVERABLE_ID,
        DATE_TRUNC('MONTH', TRY_TO_DATE(pe.DATE)) AS MONTH_START_DATE,
        SUM(pe.AMOUNT) AS ACTUAL_EXPENSES,
        SUM(CASE WHEN pe.IS_BILLABLE = 1 THEN pe.AMOUNT ELSE 0 END) AS BILLABLE_EXPENSES,
        SUM(CASE WHEN pe.IS_BILLABLE = 0 THEN pe.AMOUNT ELSE 0 END) AS NON_BILLABLE_EXPENSES
    FROM CONSULTING_DB_INITIAL.CONSULTING.PROJECTEXPENSE pe
    WHERE TRY_TO_DATE(pe.DATE) IS NOT NULL
    GROUP BY
        pe.PROJECTID,
        pe.DELIVERABLEID,
        DATE_TRUNC('MONTH', TRY_TO_DATE(pe.DATE))
),

fact_base AS (
    SELECT
        d.DELIVERABLE_ID,
        d.PROJECT_ID,
        h.MONTH_START_DATE,
        h.ACTUAL_HOURS,
        COALESCE(e.ACTUAL_EXPENSES, 0) AS ACTUAL_EXPENSES,
        COALESCE(e.BILLABLE_EXPENSES, 0) AS BILLABLE_EXPENSES,
        COALESCE(e.NON_BILLABLE_EXPENSES, 0) AS NON_BILLABLE_EXPENSES
    FROM {{ ref('dim_deliverable') }} d
    JOIN actual_hours_by_month h
        ON d.DELIVERABLE_ID = h.DELIVERABLE_ID
    LEFT JOIN expenses_by_month e
        ON d.DELIVERABLE_ID = e.DELIVERABLE_ID
       AND d.PROJECT_ID = e.PROJECT_ID
       AND h.MONTH_START_DATE = e.MONTH_START_DATE

    UNION

    SELECT
        d.DELIVERABLE_ID,
        d.PROJECT_ID,
        e.MONTH_START_DATE,
        COALESCE(h.ACTUAL_HOURS, 0) AS ACTUAL_HOURS,
        e.ACTUAL_EXPENSES,
        e.BILLABLE_EXPENSES,
        e.NON_BILLABLE_EXPENSES
    FROM {{ ref('dim_deliverable') }} d
    JOIN expenses_by_month e
        ON d.DELIVERABLE_ID = e.DELIVERABLE_ID
       AND d.PROJECT_ID = e.PROJECT_ID
    LEFT JOIN actual_hours_by_month h
        ON d.DELIVERABLE_ID = h.DELIVERABLE_ID
       AND e.MONTH_START_DATE = h.MONTH_START_DATE
)

SELECT
    ROW_NUMBER() OVER (
        ORDER BY fb.PROJECT_ID, fb.DELIVERABLE_ID, fb.MONTH_START_DATE
    ) AS PROJECT_DELIVERY_SNAPSHOT_KEY,

    dp.PROJECT_KEY,
    dd.DELIVERABLE_KEY,
    dc.CLIENT_KEY,
    dbu.BUSINESS_UNIT_KEY,
    dt.DATE_KEY,

    fb.PROJECT_ID,
    fb.DELIVERABLE_ID,
    fb.MONTH_START_DATE,

    dd.PLANNED_HOURS,
    fb.ACTUAL_HOURS,
    fb.ACTUAL_EXPENSES,
    fb.BILLABLE_EXPENSES,
    fb.NON_BILLABLE_EXPENSES,

    dd.DELIVERABLE_PROGRESS AS PROGRESS,

    GREATEST(
        dd.PLANNED_HOURS
        - SUM(fb.ACTUAL_HOURS) OVER (
            PARTITION BY fb.DELIVERABLE_ID
            ORDER BY fb.MONTH_START_DATE
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ),
        0
    ) AS FORECAST_HOURS_REMAINING,

    DATEDIFF(
        'DAY',
        dd.DUE_DATE,
        COALESCE(dd.SUBMISSION_DATE, LAST_DAY(fb.MONTH_START_DATE))
    ) AS SCHEDULE_VARIANCE_DAYS,

    CASE
        WHEN dd.SUBMISSION_DATE IS NOT NULL
             AND dd.SUBMISSION_DATE > dd.DUE_DATE THEN 1
        WHEN dd.SUBMISSION_DATE IS NULL
             AND LAST_DAY(fb.MONTH_START_DATE) > dd.DUE_DATE
             AND dd.DELIVERABLE_STATUS <> 'Completed' THEN 1
        ELSE 0
    END AS IS_DELAYED

FROM fact_base fb
JOIN {{ ref('dim_deliverable') }} dd
    ON fb.DELIVERABLE_ID = dd.DELIVERABLE_ID
   AND fb.PROJECT_ID = dd.PROJECT_ID
JOIN {{ ref('dim_project') }} dp
    ON fb.PROJECT_ID = dp.PROJECT_ID
JOIN {{ ref('dim_client') }} dc
    ON dp.CLIENT_ID = dc.CLIENT_ID
JOIN {{ ref('dim_business_unit') }} dbu
    ON dp.BUSINESS_UNIT_ID = dbu.BUSINESS_UNIT_ID
JOIN {{ ref('dim_date') }} dt
    ON fb.MONTH_START_DATE = dt.MONTH_START_DATE
WHERE fb.MONTH_START_DATE IS NOT NULL
